// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfeACZV_1ZkTxejHXI3GN6aH82EUZAHBk',
    appId: '1:336469570482:web:21d22a6a805a7c965beaab',
    messagingSenderId: '336469570482',
    projectId: 'mushu-app-c120c',
    authDomain: 'mushu-app-c120c.firebaseapp.com',
    storageBucket: 'mushu-app-c120c.appspot.com',
    measurementId: 'G-Z8C7V2J3RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX5hMChz_R4Zf_yOe4HVJ4Ud5ru8qItMw',
    appId: '1:336469570482:android:9e181bfbb9c6cd055beaab',
    messagingSenderId: '336469570482',
    projectId: 'mushu-app-c120c',
    storageBucket: 'mushu-app-c120c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjl4cCG215k-6rBcBuDTWxchA65T3C54',
    appId: '1:336469570482:ios:754f6b7c6dab7a625beaab',
    messagingSenderId: '336469570482',
    projectId: 'mushu-app-c120c',
    storageBucket: 'mushu-app-c120c.appspot.com',
    iosBundleId: 'com.example.mushuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgjl4cCG215k-6rBcBuDTWxchA65T3C54',
    appId: '1:336469570482:ios:370b3e21458f54d45beaab',
    messagingSenderId: '336469570482',
    projectId: 'mushu-app-c120c',
    storageBucket: 'mushu-app-c120c.appspot.com',
    iosBundleId: 'com.soas.mushuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfeACZV_1ZkTxejHXI3GN6aH82EUZAHBk',
    appId: '1:336469570482:web:bdc7f6a6ef6c93ae5beaab',
    messagingSenderId: '336469570482',
    projectId: 'mushu-app-c120c',
    authDomain: 'mushu-app-c120c.firebaseapp.com',
    storageBucket: 'mushu-app-c120c.appspot.com',
    measurementId: 'G-5SXDXZRPB1',
  );
}
